// module.exports = {
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };


const sidebars = 
{
  docs: 
  [
      {
      type: "category",
      label: "Getting Started",
      items: [
        "introduction",
        "quickstart",
        "freetrial",
        "faqs",
      ],
    },
    
      {
      type: "category",
      label: "Pricing & Plans",
      items: [
        "plans",
        "billing-and-quotas",
        "connectors",
        "limits-and-features",
        "monitor-usage",
        "troubleshooting",
      ],
    },    

    "billing-cancellation-refund",

    {
      type: "category",
      label: "Legal",
      items: [
        "terms-and-services",
        "security-privacy",
        "integrated-data-processing",
      ],
    },

  ],
};

export default sidebars;
