// module.exports = {
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };


const sidebars = 
{
  docs: 
  [
    {
      type: "category",
      label: "Getting Started",
      items: 
      [
        "getting-started/introduction",
        "getting-started/quickstart",
        "getting-started/freetrial",
        "getting-started/faqs",
      ],
    },
      {
      type: "category",
      label: "Using Unite",
      items: 
      [
        "using-unite/dashboard",
        { type: "category",
          label: "Data Sources",
          items: [
            "using-unite/data-sources/overview",
          {type: "category",
          label: "Google Ads",
           items: [
            "using-unite/data-sources/google-ads/setup-gads",
            "using-unite/data-sources/google-ads/prebuilt-reports",
                  ] 
          },
          {type: "category",
          label: "Google Analytics 4",
           items: [
            "using-unite/data-sources/google-analytics-4/setup-ga4",
            "using-unite/data-sources/google-analytics-4/prebuilt-reports",
                  ] 
          },
          {type: "category",
          label: "Google Search Console",
           items: [
            "using-unite/data-sources/google-search-console/setup-gsc",
            "using-unite/data-sources/google-search-console/prebuilt-reports",
           ] 
          },
          {type: "category",
          label: "Meta Ads",
           items: [
            "using-unite/data-sources/meta-ads/setup-meta",
           ] 
          },
          {type: "category",
          label: "Hubspot",
           items: [
            "using-unite/data-sources/hubspot/setup-hubspot",
           ] 
          },
          ],
        },
        "using-unite/destinations",
        "using-unite/pipelines",
        "using-unite/alerts",
        {
          type: "category",
          label: "User Management",
          items: [
            "using-unite/managing-user",
            "using-unite/roles-permissions",
          ],
        },
        "using-unite/profile-settings",
        "using-unite/support-tickets",
      ],
    },  

      {
      type: "category",
      label: "Pricing & Plans",
      items: [
        "pricing-plans/plans",
        "pricing-plans/billing-and-quotas",
        "pricing-plans/limits-and-features",
        "pricing-plans/monitor-usage",
        "pricing-plans/troubleshooting",
      ],
    },   

    "billing-cancellation-refund",

    {
      type: "category",
      label: "Legal",
      items: [
        "legal/terms-and-services",
        "legal/security-privacy",
        "legal/integrated-data-processing",
      ],
    },
  ],
};

export default sidebars;
