// module.exports = {
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };


const sidebars = 
{
  docs: 
  [
    {
      type: "category",
      label: "Getting Started",
      items: 
      [
        "getting-started/introduction",
        "getting-started/quickstart",
        "getting-started/freetrial",
        "getting-started/faqs",
      ],
    },
      {
      type: "category",
      label: "Using Unite",
      items: 
      [
        "using-unite/dashboard",
        "using-unite/data-sources",
        "using-unite/destinations",
        "using-unite/pipelines",
        "using-unite/alerts",
        {
          type: "category",
          label: "User Management",
          items: [
            "using-unite/managing-user",
            "using-unite/roles-permissions",
          ],
        },
        "using-unite/profile-settings",
        "using-unite/support-tickets",
      ],
    },  

      {
      type: "category",
      label: "Pricing & Plans",
      items: [
        "pricing-plans/plans",
        "pricing-plans/billing-and-quotas",
//      "pricing-plans/connectors",
        "pricing-plans/limits-and-features",
        "pricing-plans/monitor-usage",
        "pricing-plans/troubleshooting",
      ],
    },   

    "billing-cancellation-refund",

    {
      type: "category",
      label: "Legal",
      items: [
        "legal/terms-and-services",
        "legal/security-privacy",
        "legal/integrated-data-processing",
      ],
    },
  ],
};

export default sidebars;
